/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  theme: {
    extend: {
      colors: {
        "on-primary-container": "#7c839b",
        "inverse-primary": "#bec6e0",
        "on-primary-fixed": "#131b2e",
        "on-primary-fixed-variant": "#3f465c",
        "tertiary-fixed": "#ffddb8",
        "surface-container-lowest": "#ffffff",
        "surface-container-high": "#dce9ff",
        "tertiary-fixed-dim": "#ffb95f",
        "surface-container-highest": "#d3e4fe",
        "secondary-container": "#6cf8bb",
        "on-surface-variant": "#45464d",
        "secondary": "#006c49",
        "primary-fixed": "#dae2fd",
        "primary-fixed-dim": "#bec6e0",
        "primary-container": "#131b2e",
        "on-error-container": "#93000a",
        "tertiary-container": "#2a1700",
        "surface-container": "#e5eeff",
        "primary": "#000000",
        "on-tertiary-fixed": "#2a1700",
        "on-tertiary-fixed-variant": "#653e00",
        "on-error": "#ffffff",
        "outline-variant": "#c6c6cd",
        "surface-bright": "#f8f9ff",
        "on-tertiary-container": "#b87500",
        "surface-variant": "#d3e4fe",
        "on-surface": "#0b1c30",
        "on-secondary-fixed": "#002113",
        "on-background": "#0b1c30",
        "secondary-fixed-dim": "#4edea3",
        "error": "#ba1a1a",
        "surface-tint": "#565e74",
        "on-secondary-container": "#00714d",
        "on-primary": "#ffffff",
        "outline": "#76777d",
        "error-container": "#ffdad6",
        "background": "#f8f9ff",
        "surface": "#f8f9ff",
        "surface-dim": "#cbdbf5",
        "on-tertiary": "#ffffff",
        "secondary-fixed": "#6ffbbe",
        "on-secondary-fixed-variant": "#005236",
        "tertiary": "#000000",
        "inverse-surface": "#213145",
        "on-secondary": "#ffffff",
        "inverse-on-surface": "#eaf1ff",
        "surface-container-low": "#eff4ff",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        sm: "8px",
        xs: "4px",
        base: "4px",
        lg: "24px",
        md: "16px",
        gutter: "16px",
        xl: "40px",
        "margin-desktop": "32px",
        "margin-mobile": "16px",
      },
      fontFamily: {
        "headline-md": ["Inter"],
        "data-mono": ["JetBrains Mono"],
        "body-sm": ["Inter"],
        "headline-lg": ["Inter"],
        "body-lg": ["Inter"],
        display: ["Inter"],
        "body-md": ["Inter"],
        "label-caps": ["Inter"],
      },
      fontSize: {
        "headline-md": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "data-mono": ["13px", { lineHeight: "16px", fontWeight: "500" }],
        "body-sm": ["12px", { lineHeight: "16px", fontWeight: "400" }],
        "headline-lg": ["28px", { lineHeight: "36px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        display: ["36px", { lineHeight: "44px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "label-caps": ["11px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "700" }],
      },
    },
  },
  plugins: [require("@tailwindcss/forms"), require("@tailwindcss/container-queries")],
};
